# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Ingred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingred_name', models.CharField(max_length=300)),
                ('ingred_amt', models.FloatField()),
                ('ingred_unit', models.CharField(choices=[('cup', 'cup'), ('gram', 'gram'), ('container', 'container'), ('oz', 'oz'), ('fl oz', 'fl oz'), ('pnt', 'pnt'), ('item', 'item'), ('tblsp', 'tblsp')], max_length=100)),
                ('cal', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fat', models.FloatField()),
                ('protein', models.FloatField()),
                ('sugar', models.FloatField()),
                ('min_amt', models.FloatField()),
                ('max_amt', models.FloatField()),
                ('standalone', models.BooleanField(default=True)),
                ('submit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(default='Unnamed', max_length=300)),
                ('prep_time', models.CharField(blank=True, choices=[('long', 'long'), ('short', 'short'), ('none', 'none')], max_length=300)),
                ('ingred', models.ManyToManyField(to='planmaker.Ingred')),
                ('submit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='after_dinner_snack',
            field=models.ManyToManyField(blank=True, related_name='after_dinner_snack_recipes', to='planmaker.Recipe'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='afternoon_snack',
            field=models.ManyToManyField(blank=True, related_name='afternoon_snack_recipes', to='planmaker.Recipe'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='breakfast',
            field=models.ManyToManyField(blank=True, related_name='breakfast_recipes', to='planmaker.Recipe'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='dinner',
            field=models.ManyToManyField(blank=True, related_name='dinner_recipes', to='planmaker.Recipe'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='lunch',
            field=models.ManyToManyField(blank=True, related_name='lunch_recipes', to='planmaker.Recipe'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='mid_morning_snack',
            field=models.ManyToManyField(blank=True, related_name='mid_morning_snack_recipes', to='planmaker.Recipe'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
