



column_name_lookup = {
"Water":"water", 
"Energy":"kilocalories", 
"Energy":"kilojoules", 
"Protein":"protein_g", 
"Total lipid (fat)":"fat_g", 
"Ash":"ash_g", 
"Carbohydrate, by difference":"carb_g", 
"Fiber, total dietary":"fiber_g", 
"Sugars, total":"sugar_g", 
"Sucrose":"sucrose_g", 
"Glucose (dextrose)":"glucose_g", 
"Fructose":"fructose_g", 
"Lactose":"lactose_g", 
"Maltose":"maltose_g", 
"Galactose":"galactose_g", 
"Starch":"starch_g", 
"Calcium, Ca":"calcium_mg", 
"Iron, Fe":"iron_mg", 
"Magnesium, Mg":"magnesium_mg", 
"Phosphorus, P":"phosphorus_mg", 
"Potassium, K":"potassium_mg", 
"Sodium, Na":"sodium_mg", 
"Zinc, Zn":"zinc_mg", 
"Copper, Cu":"copper_mg", 
"Manganese, Mn":"manganese_mg", 
"Selenium, Se":"selenium_mcg", 
"Fluoride, F":"flouride_mcg", 
"Vitamin C, total ascorbic acid":"vit_c_mg", 
"Thiamin":"thiamin_mg", 
"Riboflavin":"riboflavin_mg", 
"Niacin":"niacin_mg", 
"Pantothenic acid":"panto_acid_mg", 
"Vitamin B-6":"vit_b6_mg", 
"Folate, total":"folate_mcg", 
"Folic acid":"folic_acid_mcg", 
"Folate, food":"food_folate_mcg", 
"Folate, DFE":"folate_mcg_dfe", 
"Choline, total":"choline_mcg", 
"Betaine":"betaine_mg", 
"Vitamin B-12":"vit_b12_mcg", 
"Vitamin B-12, added":"vit_b12_added_mcg", 
"Vitamin A, RAE":"vit_a_mcg_rae", 
"Retinol":"retinol_mcg", 
"Carotene, beta":"beta_carotene_mcg", 
"Carotene, alpha":"alpha_carotene_mcg", 
"Cryptoxanthin, beta":"beta_cryptoxanthin_mcg", 
"Vitamin A, IU":"vit_a_iu", 
"Lycopene":"lycopene_mcg", 
"Lutein + zeaxanthin":"lutein_zeazanthin_mcg", 
"Vitamin E (alpha-tocopherol)":"vit_e_mg", 
"Vitamin E, added":"", 
"Tocopherol, beta":"beta_tocopherol_mg", 
"Tocopherol, gamma":"gamma_tocopherol_mg", 
"Tocopherol, delta":"delta_tocopherol_mg", 
"Tocotrienol, alpha":"alpha_tocopherol_mg", 
"Tocotrienol, beta":"beta_tocotrienol_mg", 
"Tocotrienol, gamma":"gamma_tocotrienol_mg", 
"Tocotrienol, delta":"delta_tocotrienol_mg", 
"Vitamin D (D2 + D3)":"vit_d_mcg", 
"Vitamin D2 (ergocalciferol)":"vit_d2_mcg", 
"Vitamin D3 (cholecalciferol)":"vit_d3_mcg", 
"Vitamin D":"vit_d_ui", 
"Vitamin K (phylloquinone)":"vit_k_mcg", 
"Dihydrophylloquinone":"dihydrophylloquinone_mcg", 
"Menaquinone-4":"menaquinone_4_mcg", 
"Fatty acids, total saturated":"saturated_fatty_acid_g", 
"4:0":"ratio_4_0_g", 
"6:0":"ratio_6_0_g", 
"8:0":"ratio_8_0_g", 
"10:0":"ratio_10_0_g", 
"12:0":"ratio_12_0_g", 
"13:0":"ratio_13_0_g", 
"14:0":"ratio_14_0_g", 
"15:0":"ratio_15_0_g", 
"16:0":"ratio_16_0_g", 
"17:0":"ratio_17_0_g", 
"18:0":"ratio_18_0_g", 
"20:0":"ratio_20_0_g", 
"22:0":"ratio_22_0_g", 
"24:0":"ratio_24_0_g", 
"Fatty acids, total monounsaturated":"monosaturated_fatty_acid_g", 
"14:1":"ratio_14_1_g", 
"15:1":"ratio_15_1_g", 
"16:1 undifferentiated":"ratio_16_1_undif_g", 
"16:1 c":"ratio_16_1_c_g", 
"16:1 t":"ratio_16_1_t_g", 
"17:1":"ratio_17_1_g", 
"18:1 undifferentiated":"ratio_18_1_undif_g", 
"18:1 c":"ratio_18_1_c_g", 
"18:1 t":"ratio_18_1_t_g", 
"18:1-11 t (18:1t n-7)":"", 
"20:1":"", 
"22:1 undifferentiated":"", 
"22:1 c":"", 
"22:1 t":"", 
"24:1 c":"", 
"Fatty acids, total polyunsaturated":"polysaturated_fatty_acid_g", 
"18:2 undifferentiated":"ratio_18_2_undif_g", 
"18:2 n-6 c,c":"ratio_18_2_n_6_cc_g", 
"18:2 CLAs":"ratio_18_2_cla_g", 
"18:2 t,t":"ratio_18_2_t_t_g", 
"18:2 i":"ratio_18_2_i_g", 
"18:2 t not further defined":"ratio_18_2_not_def_g", 
"18:3 undifferentiated":"ratio_18_3_undif_g", 
"18:3 n-3 c,c,c (ALA)":"ratio_18_3_n3_ccc_g", 
"18:3 n-6 c,c,c":"ratio_18_3_n6_ccc_g", 
"18:3i":"ratio_18_3_i_g", 
"18:4":"ratio_18_4_g", 
"20:2 n-6 c,c":"ratio_20_2_n6_cc_g", 
"20:3 undifferentiated":"ratio_20_3_undif_g", 
"20:3 n-3":"ratio_20_3_n3_g", 
"20:3 n-6":"ratio_20_3_n6_g", 
"20:4 undifferentiated":"ratio_20_4_undif_g", 
"20:4 n-6":"ratio_20_4_n6_g", 
"20:5 n-3 (EPA)":"ratio_20_5_n3_epa_g", 
"21:5":"ratio_21_5_g", 
"22:4":"ratio_22_4_g", 
"22:5 n-3 (DPA)":"ratio_22_5_n3_dpa_g", 
"22:6 n-3 (DHA)":"ratio_22_6_n3_dha_g", 
"Fatty acids, total trans":"trans_fatty_acid_g", 
"Fatty acids, total trans-monoenoic":"trans_monoenoic_fatty_acid_g", 
"Fatty acids, total trans-polyenoic":"trans_polyenoic_fatty_acid_g", 
"Cholesterol":"cholesterol_mg", 
"Phytosterols":"phytosterols_mg", 
"Stigmasterol":"stigmasterol_mg", 
"Campesterol":"campesterol_mg", 
"Beta-sitosterol":"beta_sitosterol_mg", 
"Tryptophan":"tryptophan_g", 
"Threonine":"threonine_g", 
"Isoleucine":"isoleucine_g", 
"Leucine":"leucine_g", 
"Lysine":"lysine_g", 
"Methionine":"methionine_g", 
"Cystine":"cystine_g", 
"Phenylalanine":"phenylalanine_g", 
"Tyrosine":"tyrosine_g", 
"Valine":"valine_g", 
"Arginine":"arginine_g", 
"Histidine":"histidine_g", 
"Alanine":"alanine_g", 
"Aspartic acid":"aspartic_acid_g", 
"Glutamic acid":"glutamic_acid_g", 
"Glycine":"glycine_g", 
"Proline":"proline_g", 
"Serine":"serine_g", 
"Hydroxyproline":"hydroxyproline_g", 
"Alcohol, ethyl":"ethyl_alcohol_g", 
"Caffeine":"caffeine_mg", 
"Theobromine":"theobromine_mg", 

}

