# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 15:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition_Req',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('daily_cal', models.IntegerField()),
                ('daily_carb', models.IntegerField()),
                ('daily_fat', models.IntegerField()),
                ('daily_protein', models.IntegerField()),
                ('daily_sugar', models.IntegerField(default=40)),
                ('flex_perc', models.FloatField(default=0.005)),
            ],
        ),
    ]
